[theme]
primaryColor = "#7A2331"
backgroundColor = "#FBF8F3"
secondaryBackgroundColor = "#F1E7D8"
textColor = "#241A17"
font = "Montserrat:https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
